substitutions:
  device_name:              Comfospot
  friendly_name_fan:        Comfospot
  gpio_led1:                GPIO0
  gpio_led2:                GPIO3
  gpio_led3:                GPIO1
  gpio_led4:                GPIO4
  gpio_led_filter_change:   GPIO10
  gpio_led_error:           GPIO7 
  gpio_output_plus:         GPIO5
  gpio_output_minus:        GPIO6
  gpio_status_led:          GPIO8

packages:
  restart_buttons:        !include restart.yaml
  comfospot_50:           !include Comfospot_50.yaml
  status led:             !include status_led.yaml

esphome:
  name: comfospot
  friendly_name: Comfospot
  platformio_options: 
    board_build.flash_mode: dio
    board_build.f_cpu: 80000000L

  project:
    name: thatslolo.comfospot-50
    version: "0.8"


esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    sdkconfig_options: 
      CONFIG_ESP32C3_DEFAULT_CPU_FREQ_MHZ: "80"
      CONFIG_ESP32C3_DEFAULT_CPU_FREQ_80: y

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG

# Enable Home Assistant API
api:

ota:

dashboard_import:
  package_import_url: github://esphome/esphome-project-template/project-template-esp32.yaml@v6
  import_full_config: false # or true

wifi:
  ap:
    ssid: "Comfospot"
    password: ""

captive_portal:

esp32_improv:
  authorizer: none

improv_serial: